version: '3.8'

services:
  consul:
    image: consul:1.14
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - CURRENT_RUN=development
      - DEV_PORT=8080
      - DEV_HOST=localhost
      - DEV_API_URL=http://users:8081
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - users
      - consul
    networks:
      - app-network

  users:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: users
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ENV=development
      - CURRENT_RUN=development
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=users
      - SERVICE_PORT=8081
      - USERS_PORT=8081
    depends_on:
      - consul
    networks:
      - app-network

networks:
  app-network:
    driver: bridge